config/routes.rb
Rails.application.routes.draw do

  resources :tags
  resources :api_tokens
  resources :projects
  resources :tasks
  resources :users
  resources :documents

  post '/documents/api_markdown', to: 'documents#api_markdown'
  root 'tasks#index'
  get '/welcome', to: 'welcome#index', as: :welcome
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/login', to: 'sessions#login_with_passwd_auth'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/api_token.rb
class ApiToken < ApplicationRecord
    belongs_to :user
end

app/controllers/api_tokens_controller.rb
require 'securerandom'

class ApiTokensController < ApplicationController
  before_action :set_api_token, only: %i[ show edit update destroy ]

  # GET /api_tokens or /api_tokens.json
  def index
    @api_tokens = ApiToken.where(user: current_user)
  end

  # GET /api_tokens/1 or /api_tokens/1.json
  def show
  end

  # GET /api_tokens/new
  def new
    @api_token = ApiToken.new
  end

  # GET /api_tokens/1/edit
  def edit
  end

  # POST /api_tokens or /api_tokens.json
  def create
    #@api_token = ApiToken.new(api_token_params)
    @api_token = ApiToken.create(secret: "rask-"+ SecureRandom.uuid, description: params[:api_token][:description], expired_at: Time.zone.now.next_year, user_id: current_user.id)

    respond_to do |format|
      if @api_token
        format.html { redirect_to @api_token, notice: "Apiトークンを追加しました．" }
        format.json { render :show, status: :created, location: @api_token }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @api_token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api_tokens/1 or /api_tokens/1.json
  def update
    respond_to do |format|
      if @api_token.update(api_token_params)
        format.html { redirect_to @api_token, notice: "Apiトークンを更新しました．" }
        format.json { render :show, status: :ok, location: @api_token }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @api_token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api_tokens/1 or /api_tokens/1.json
  def destroy
    @api_token.destroy
    respond_to do |format|
      format.html { redirect_to api_tokens_url, notice: "Apiトークンを削除しました．" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api_token
      @api_token = ApiToken.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def api_token_params
      params.require(:api_token).permit(:secret, :description, :expired_at, :user_id)
    end
end

app/helpers/api_tokens_helper.rb
module ApiTokensHelper
end

app/views/api_tokens/_form.html.erb
<%= form_with(model: api_token) do |form| %>
  <% if api_token.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(api_token.errors.count, "error") %> prohibited this api_token from being saved:</h2>

      <ul>
        <% api_token.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description, "トークン名", class: "h5 font-weight-bold" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "保存", class: "btn btn-danger btn-block" %>
  </div>
<% end %>

app/views/api_tokens/edit.html.erb
<%= render 'layouts/h1', title: "トークン名編集" %>

<%= render 'form', api_token: @api_token %>

app/views/api_tokens/index.html.erb
<div class="d-flex justify-content-between">
  <% if logged_in? %>
    <%= render 'layouts/h1', title: "APIトークン一覧(#{current_user[:name]})" %>
  <% else %>
    <%= render 'layouts/h1', title: "APIトークン一覧" %>
  <% end %>
  <%= link_to '新規作成', new_api_token_path, class: "my-auto btn btn-danger" %>
</div>

<% @api_tokens.each do |api_token| %>
  <% if logged_in? %>
    <div class="card my-3">
      <div class="card-body d-flex">
        <div>
          <p><strong>APIトークン:</strong> <%= api_token.secret %></p>
          <p><strong>トークン名:</strong> <%= api_token.description %></p>
          <p><strong>有効期限:</strong> <%= api_token.expired_at %></p>
        </div>
        <div class="ml-auto">
          <%= link_to '編集', edit_api_token_path(api_token), class: "btn btn-sm" %>
          <%= button_to '削除', api_token, method: :delete, data: { turbo_confirm: 'このAPIトークンを削除しますか？' }, class: "btn btn-sm" %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/api_tokens/new.html.erb
<%= render 'layouts/h1', title: "APIトークン新規作成" %>

<%= render 'form', api_token: @api_token %>

app/views/api_tokens/show.html.erb
<div class="my-3">
  <p class="h5 font-weight-bold mb-2">作成者</p>
  <%= link_to @api_token.user.name, user_path(@api_token.user) %>

  <p class="h5 font-weight-bold mb-2">APIトークン</p>
  <p><%= @api_token.secret %></p>

  <p class="h5 font-weight-bold mb-2">トークン名</p>
  <p><%= @api_token.description %></p>

  <p class="h5 font-weight-bold mb-2">有効期限</p>
  <p><%= @api_token.expired_at %></p>
</div>

<%= link_to '編集', edit_api_token_path(@api_token), class: "btn btn-sm" %> |
<%= link_to '戻る', api_tokens_path, class: "btn btn-sm" %>