config/routes.rb
Rails.application.routes.draw do

  resources :tags
  resources :api_tokens
  resources :projects
  resources :tasks
  resources :users
  resources :documents

  post '/documents/api_markdown', to: 'documents#api_markdown'
  root 'tasks#index'
  get '/welcome', to: 'welcome#index', as: :welcome
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/login', to: 'sessions#login_with_passwd_auth'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :restrict_with_exception
  has_many :documents, dependent: :restrict_with_exception
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "tasks", "updated_at", "user_id"]
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all.includes(:user)
  end

  # GET /projects/1 or /projects/1.json
  def show
    @tasks = Task.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "プロジェクトを追加しました．" }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "プロジェクトを更新しました．" }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    begin
      @project.destroy
      respond_to do |format|
        format.html { redirect_to projects_url, notice: "プロジェクトを削除しました．" }
        format.json { head :no_content }
      end
    rescue ActiveRecord::DeleteRestrictionError => e
      respond_to do |format|
        format.html { redirect_to projects_url, alert: @project.name + "に紐づいているタスクがあるため削除できません．"}
        format.json { render json: @project.errors, status: :precondition_failed }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, "プロジェクト名", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit "保存", class: "btn btn-danger w-100" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= render 'layouts/h1', title: "プロジェクト編集" %>
  
<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<div class="d-flex justify-content-between">
  <%= render 'layouts/h1', title: "プロジェクト一覧" %>
  <div class="flex-grow-1"></div>
  <%= link_to '新規作成', new_project_path, class: "my-auto btn btn-danger" %>
</div>

<% @projects.each do |project| %>
  <div class="p-3 my-3 border rounded">
    <div class="d-flex justify-content-between">
      <div>
        <p class="h5"><%= project.name %></p>
        <p>達成率 : <%= project.tasks.count { |task| task.completed? } %> / <%= project.tasks.count %></p>
      </div>
      <div class="text-end">
        <% if logged_in? %>
          <div class="d-flex gap-2">
            <%= link_to '詳細', project, class: "btn btn-sm" %>
            <%= link_to '編集', edit_project_path(project), class: "btn btn-sm" %>
            <% if project.tasks.count != 0 %>
              <span class="text-muted btn btn-sm" style="pointer-events: none; background: none; border: none; color: inherit;">削除</span>
            <% else %>
              <%= button_to '削除', project, method: :delete, data: { turbo_confirm: 'このプロジェクトを削除しますか？' }, class: "btn btn-sm text-black" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div>
      <p id="<%= "project-#{project.id}" %>" class="mt-3 text-center cursor-pointer bg-light">+</p>
    </div>
  </div>

  <div id="<%= "project-#{project.id}-tasks" %>" class="collapse">
    <% project.tasks.each_with_index do |task, index| %>
      <div class="d-flex">
        <div class="w-1">
          <div class="h-50 border-end"></div>
          <% if index < project.tasks.count - 1 %>
            <div class="h-50 border-end"></div>
          <% end %>
        </div>
        <div class="w-1">
          <div class="h-50 border-bottom"></div>
        </div>
        <div class="p-3 my-3 border rounded d-flex">
          <div>
            <p class="h5"><%= task.content %></p>
            <p>担当者: <%= link_to task.assigner.name, task.assigner %></p>
            <p>状態: <%= task.state.name %></p>
          </div>
          <div class="flex-grow-1"></div>
          <% if logged_in? %>
            <%= link_to '詳細', task, class: "btn btn-sm" %>
            <%= link_to '編集', edit_task_path(task), class: "btn btn-sm" %>
            <%= button_to '削除', task, method: :delete, data: { turbo_confirm: 'このタスクを削除しますか？' }, class: "btn btn-sm" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<script>
  <% @projects.each do |project| %>
    document.getElementById("<%= "project-#{project.id}" %>").onclick = () => {
      const target = document.getElementById("<%= "project-#{project.id}-tasks" %>")
      target.classList.toggle("collapse") // ここでcollapseクラスをトグル
      target.classList.toggle("show") // 表示状態にするためshowクラスを追加

      const button = document.getElementById("<%= "project-#{project.id}" %>")
      button.innerText = button.innerText === "+" ? "-" : "+"
    }
  <% end %>
</script>

app/views/projects/new.html.erb
<%= render 'layouts/h1', title: "プロジェクト新規作成" %>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<%= render 'layouts/h1', title: @project.name %>

<div class="my-3">
  <p class="h5 mb-2">作成者</p>
  <%= link_to @project.user.name, @project.user %>
</div>

<div>
  <div class="d-flex justify-content-between">
    <p class="h5 mb-2">タスク一覧</p>
    <%= link_to '新規作成', new_task_path(project_id: @project.id), class: "btn btn-danger" %>
  </div>
  <% @project.tasks.each do |task| %>
    <div class="p-3 my-3 border rounded d-flex">
      <div>
        <p class="h5"><%= task.content %></p>
        <p>担当者: <%= link_to task.assigner.name, task.assigner %></p>
      </div>
      <div class="flex-grow-1"></div>
      <% if logged_in? %>
        <%= link_to '詳細', task, class: "btn btn-sm" %>
        <%= link_to '編集', edit_task_path(task), class: "btn btn-sm" %>
        <%= button_to '削除', task, method: :delete, data: { turbo_confirm: 'このタスクを削除しますか？' }, class: "btn btn-sm" %>
      <% end %>
    </div>
  <% end %>
  <%= link_to '編集', edit_project_path(@project), class: "btn btn-sm" %>
</div>