config/routes.rb
Rails.application.routes.draw do

  resources :tags
  resources :api_tokens
  resources :projects
  resources :tasks
  resources :users
  resources :documents

  post '/documents/api_markdown', to: 'documents#api_markdown'
  root 'tasks#index'
  get '/welcome', to: 'welcome#index', as: :welcome
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/login', to: 'sessions#login_with_passwd_auth'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :task_tags
  has_many :tasks, through: :task_tags, dependent: :restrict_with_exception
  has_many :document_tags
  has_many :documents, through: :document_tags, dependent: :restrict_with_exception
  validates :name, presence: true, uniqueness: true

  def self.order_by_popularity
    self.find_by_sql <<~'SQL'
      SELECT
        tags.*,
        count(DISTINCT document_tags.id) + count(DISTINCT task_tags.id) AS popularity
      FROM
        tags
        LEFT JOIN document_tags ON tags.id = document_tags.tag_id
        LEFT JOIN task_tags ON tags.id = task_tags.tag_id
      GROUP BY
        tags.id
      ORDER BY
        popularity DESC
      ;
    SQL
  end
end

app/controllers/tags_controller.rb
# coding: utf-8
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: "タグを追加しました．" }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: "タグを更新しました．" }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    begin
      @tag.destroy
      respond_to do |format|
        format.html { redirect_to tags_url, notice: "タグを削除しました．" }
        format.json { head :no_content }
      end
    rescue ActiveRecord::DeleteRestrictionError => e
      respond_to do |format|
        format.html { redirect_to tags_url, alert: @tag.name + "に紐づいているタスク，ドキュメントがあるため削除できません．"}
        format.json { render json: @tag.errors, status: :precondition_failed}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>
      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, "タグ名", class: "form-label fw-bold" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="d-grid">
    <%= form.submit "保存", class: "btn btn-danger" %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div class="p-3 my-3 border rounded d-flex justify-content-between">
  <div>
    <p class="h4"><%= link_to tag.name, tag, class: "btn btn-primary btn-lg" %></p>
    <p>タスク数 : <%= tag.tasks.count %></p>
    <p>文書数 : <%= tag.documents.count %></p>
  </div>
  <div class="flex-grow-1"></div>
  <% if logged_in? %>
    <div class="d-flex align-items-center">
      <%= link_to '詳細', tag, class: "btn btn-sm text-black" %>
      <%= link_to '編集', edit_tag_path(tag), class: "btn btn-sm mx-2 text-black" %>
      <% if tag.tasks.count == 0 && tag.documents.count == 0 %>
        <%= button_to '削除', tag, method: :delete, data: { turbo_confirm: 'このタグを削除しますか？' }, class: "btn btn-sm text-black" %>
      <% else %>
        <p class="btn btn-sm text-muted mb-0" style="pointer-events: none; background: none; border: none; color: inherit;">削除</p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tags/edit.html.erb
<%= render 'layouts/h1', title: "タグ編集" %>
  
<%= render 'form', tag: @tag %>

app/views/tags/index.html.erb
<div class="d-flex">
  <%= render 'layouts/h1', title: "タグ一覧" %>
  <div class="flex-grow-1"></div>
  <%= link_to '新規作成', new_tag_path, class: "my-auto btn btn-danger text-white" %>
</div>

<%= render @tags %>

app/views/tags/new.html.erb
<%= render 'layouts/h1', title: "タグ新規作成" %>

<%= render 'form', tag: @tag %>

app/views/tags/show.html.erb
<%= render 'layouts/h1', title: @tag.name %>

<div>
  <p class="h5 fw-bold mb-2">タグ名</p>
    <p class="h5 mb-2"><%= link_to @tag.name, @tag, class: "btn btn-lg btn-primary text-white" %></p>
</div>

<div>
  <div class="d-flex">
    <p class="h5 fw-bold mb-2">タスク一覧</p>
    <div class="flex-grow-1"></div>
  </div>
  <% @tag.tasks.each do |task| %>
    <div class="p-3 my-3 border rounded d-flex justify-content-between">
      <div>
        <p class="h5"><%= task.content %></p>
        <p>担当者: <%= link_to task.assigner.name, task.assigner %></p>
      </div>
      <div class="flex-grow-1"></div>
      <% if logged_in? %>
        <%= link_to '詳細', task, class: "btn btn-sm" %>
        <%= link_to '編集', edit_task_path(task), class: "btn btn-sm" %>
        <%= button_to '削除', task, method: :delete, data: { turbo_confirm: 'このタスクを削除しますか？' }, class: "btn btn-sm" %>
      <% end %>
    </div>
  <% end %>

  <div class="d-flex">
    <p class="h5 fw-bold mb-2">文書一覧</p>
    <div class="flex-grow-1"></div>
  </div>
  <% @tag.documents.each do |document| %>
    <div class="p-3 my-3 border rounded d-flex justify-content-between">
      <div>
        <p class="h5"><%= document.content %></p>
      </div>
      <div class="flex-grow-1"></div>
      <% if logged_in? %>
        <%= link_to '詳細', document, class: "btn btn-sm" %>
        <%= link_to '編集', edit_document_path(document), class: "btn btn-sm" %>
        <%= button_to '削除', document, method: :delete, data: { turbo_confirm: 'この文書を削除しますか？' }, class: "btn btn-sm" %>
      <% end %>
    </div>
  <% end %>

  <%= link_to '編集', edit_tag_path(@tag), class: "btn btn-sm" %>
</div>