config/routes.rb
Rails.application.routes.draw do

  resources :tags
  resources :api_tokens
  resources :projects
  resources :tasks
  resources :users
  resources :documents

  post '/documents/api_markdown', to: 'documents#api_markdown'
  root 'tasks#index'
  get '/welcome', to: 'welcome#index', as: :welcome
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/login', to: 'sessions#login_with_passwd_auth'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/action_item.rb
class ActionItem < ApplicationRecord
  after_create :set_uid
  validates :task_url, format: { with: /\A[a-zA-Z0-9\-._~:\/?#\[\]@!$&'()*+,;%=]+\z/}, allow_nil: true
  validates :uid, uniqueness: true
  before_update :prevent_uid_change

  def uid
    "%04d" % self.id
  end

  private

  def set_uid
    self.update(uid: uid)
  end

  def prevent_uid_change
    if self.uid_was.present? && self.uid_changed?
      throw(:abort)
    end
  end

end

app/models/api_token.rb
class ApiToken < ApplicationRecord
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
# coding: utf-8
class Document < ApplicationRecord
  belongs_to :user, foreign_key: 'creator_id'
  belongs_to :creator, foreign_key: 'creator_id', class_name: 'User'
  belongs_to :project, optional: true
  has_many :document_tags, dependent: :destroy
  has_many :tags, through: :document_tags
  accepts_nested_attributes_for :document_tags, allow_destroy: true

  validates :content, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validates :location, presence: true
  #validates :project, presence: true
  before_validation :add_unique_action_item_marker

  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "creator_id", "description", "end_at", "id", "location", "project_id", "start_at", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["creator", "document_tags", "project", "tags", "user"]
  end

  def add_unique_action_item_marker
    return unless self.description
    desc = ""
    self.description.each_line {|line|
      matched = line.match(/-->\(([^!]+)\)/)
      if matched != nil
        @action_item = ActionItem.create(task_url: nil)
        line.gsub!(/-->\(.+\)/, "-->(#{matched[1]} !:#{@action_item.uid})")
      end
      desc += line
    }
    self.description = desc
  end
end

app/models/document_tag.rb
class DocumentTag < ApplicationRecord
  belongs_to :document
  belongs_to :tag
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :restrict_with_exception
  has_many :documents, dependent: :restrict_with_exception
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "tasks", "updated_at", "user_id"]
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :task_tags
  has_many :tasks, through: :task_tags, dependent: :restrict_with_exception
  has_many :document_tags
  has_many :documents, through: :document_tags, dependent: :restrict_with_exception
  validates :name, presence: true, uniqueness: true

  def self.order_by_popularity
    self.find_by_sql <<~'SQL'
      SELECT
        tags.*,
        count(DISTINCT document_tags.id) + count(DISTINCT task_tags.id) AS popularity
      FROM
        tags
        LEFT JOIN document_tags ON tags.id = document_tags.tag_id
        LEFT JOIN task_tags ON tags.id = task_tags.tag_id
      GROUP BY
        tags.id
      ORDER BY
        popularity DESC
      ;
    SQL
  end
end

app/models/task.rb
# coding: utf-8

class Task < ApplicationRecord
  belongs_to :user, foreign_key: "creator_id"
  belongs_to :assigner, foreign_key: "assigner_id", class_name: "User"
  belongs_to :project, optional: true
  has_many :task_tags, dependent: :destroy
  has_many :tags, through: :task_tags
  accepts_nested_attributes_for :task_tags, allow_destroy: true
  belongs_to :state, foreign_key: "task_state_id", class_name: "TaskState"

  scope :desc, ->(limit = nil) { order(updated_at: "DESC").limit(limit) }
  scope :asc, ->(limit = nil) { order(updated_at: "ASC").limit(limit) }
  scope :active, -> { joins(:state).where(state: { name: "todo" }) }

  validates :content, presence: true

  def self.ransackable_attributes(auth_object = nil)
    [ "assigner_id", "content", "created_at", "creator_id", "description", "due_at", "id", "project_id", "tag_id", "task_state_id", "updated_at" ]
    end

  def self.ransackable_associations(auth_object = nil)
    [ "assigner", "project", "state", "tags", "task_tags", "user" ]
  end

  def show_days_ago
    ((Time.zone.now - self.created_at)/60/60/24)
  end
  def days_to_deadline
    return Float::INFINITY unless self.due_at
    ((self.due_at - Time.zone.now)/60/60/24)
  end

  def overdue?
    return false unless self.due_at
    Time.zone.now.after?(self.due_at)
  end

  def completed?
    self.state.name == "done"
  end
end

app/models/task_state.rb
class TaskState < ApplicationRecord
  has_many :tasks, dependent: :restrict_with_exception

  validates :name, presence: true
  validates :priority, presence: true
end

app/models/task_tag.rb
class TaskTag < ApplicationRecord
  belongs_to :task
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password validations: false

  # github action uses the provider name "github"
  validate do |record|
    if record.password_digest.blank? && record.provider != "github" then
      record.errors.add(:base, "Password is blank and provider is not GitHub")
    end
  end
  validates_length_of :password, maximum: ActiveModel::SecurePassword::MAX_PASSWORD_LENGTH_ALLOWED
  validates_confirmation_of :password, allow_blank: true

  validates :provider, presence: true

  has_many :assigned_tasks, foreign_key: "assigner_id", class_name: "Task"
  has_many :tasks, foreign_key: "creator_id"
  has_many :projects
  has_many :api_tokens, foreign_key: "user_id"
  has_many :documents, foreign_key: "creator_id"
  validates :screen_name, uniqueness: true
  validates :uid, uniqueness: true, presence: true
  validates :name, presence: true, uniqueness: true
  validates :screen_name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    [ "active", "avatar_url", "created_at", "id", "id_value", "name", "password_digest", "provider", "screen_name", "uid", "updated_at" ]
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid      = auth["uid"]

      info = auth["info"]
      user.name        = info["name"] || info["nickname"]
      user.screen_name = info["nickname"]
      user.avatar_url  = info["image"]
    end
  end
end

app/helpers/api_tokens_helper.rb
module ApiTokensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tag_label(tag)
    raw %(<span class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"> #{tag.name}</span>)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) || ApiToken.find_by_secret(params[:api_token])&.user
  end

  def current_user?(user)
    user && user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def days_to_deadline_as_string(task)
    days = task.days_to_deadline
    if days.finite?
      "期限まで後" + days.round.to_s + "日です！"
    else
      ""
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div class = "alert alert-warning">
        <ul>
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_h1.html.erb
<h1 class="text-lg fw-bold py-3"><%= title %></h1>

app/views/layouts/_header.html.erb
<nav class="navbar sticky-top navbar-expand-sm navbar-light bg-danger mb-3 z-50">
  <%= link_to "Rask", tasks_path, class: "navbar-brand text-black" %>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to "プロジェクト", projects_path, method: :get, class: "nav-link text-black" %></li>
      <li class="nav-item"><%= link_to "タスク一覧", tasks_path, method: :get, class: "nav-link text-black" %></li>
      <li class="nav-item"><%= link_to "文書一覧", documents_path, method: :get, class: "nav-link text-black" %></li>
      <li class="nav-item"><%= link_to "タグ一覧", tags_path, method: :get, class: "nav-link text-black" %></li>
      <li class="nav-item"><%= link_to "ユーザ一覧", users_path, method: :get, class: "nav-link text-black" %></li>
      <li class="nav-item"><%= link_to "APIトークン一覧", api_tokens_path, method: :get, class: "nav-link text-black" %></li>
      <li class="nav-item"><%= link_to "Raskについて(GitHub)", 'https://github.com/nomlab/rask/blob/main/README.md', method: :get, class: "nav-link text-black" %></li>
    </ul>
    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
        <%= link_to 'タスクを作成', new_task_path, class: 'btn btn-light me-2' %>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "ログアウト (#{current_user.screen_name})", logout_path, class: 'btn', data: { "turbo-method": :delete, "turbo-confirm": 'ログアウトしますか？' } %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= button_to "ログイン", '/auth/github', class: 'btn', data: { "turbo": false } %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_tag_list.html.erb
<div class="border mx-auto p-3 overflow-auto">
  <p class="fw-bold fs-4 mb-3">タグ一覧</p>
  <div class="d-flex flex-wrap gap-1">
    <% Tag.order_by_popularity.each do |tag| %>
      <%= link_to tag_label(tag), tag, class: "btn btn-primary btn-outline-primary btn-lg" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rask" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" crossorigin="anonymous" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tab", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tasks", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "users", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "jfm", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "github-markdown", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |message_type, message| %>
      <% message_color = { notice: "alert-info", success: "alert-success", danger: "alert-danger", alert: "alert-warning" } %>
      <div class="alert <%= message_color[message_type.to_sym] %> m-3" role="alert">
        <%= message %>
      </div>
    <% end %>

    <div class="container-fluid">
      <div class="row">
        <aside class="col-md-3 p-3">
          <%= render 'layouts/tag_list' %>
        </aside>

        <main class="col-md-9">
          <div class="container p-5">
            <%= yield %>
          </div>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'tab' %>
    <%= stylesheet_link_tag 'tasks' %>
    <%= stylesheet_link_tag 'users' %>
    <%= stylesheet_link_tag 'jfm' %>
    <%= stylesheet_link_tag 'github-markdown' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <% message_color = {:notice => "primary", :success => "primary", :danger => "warning", :alert => "danger"} %>
      <p class="m-3 p-3 bg-<%= message_color[message_type.to_sym] %> text-white rounded">
        <%= message %>
      </p>
    <% end %>
    <div class="container-lg px-4 py-3">
      <%= yield %>
    </div>
  </body>
</html>